# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

username: admin
password: admin
port: 57400
timeout: 10s
#skip-verify: true
encoding: json_ietf
insecure: true

targets:
  clab-sr-R1:57400:
  clab-sr-R2:57400:
  clab-sr-R3:57400:
  clab-sr-R4:57400:
  clab-sr-R5:57400:
  clab-sr-R6:57400:

subscriptions:
        
  sros_port_stats:
    paths:
      - /state/port[port-id=*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_if_stats:
    paths:
      - /state/router[router-name=Base]/interface[interface-name=*]/statistics
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_if_oper_state:
    paths:
      - /state/router[router-name=*]/interface[interface-name=*]/oper-state
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_if_delay:
    paths:
      - /state/router[router-name=Base]/interface[interface-name=*]/if-attribute/delay
    mode: stream
    stream-mode: sample
    sample-interval: 5s

  sros_route_metric:
    paths:
      - /state/router[router-name=Base]/tunnel-table/ipv4/tunnel[ipv4-prefix=*][list-index=1][nexthop-index=0]/metric
    mode: stream
    stream-mode: sample
    sample-interval: 5s

outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
      - up-down-map
  # stdout:
  #   type: file
  #   file-type: stdout
  #   event-processors:
  #     - proc-convert-strings-to-int
  #     - trim-prefixes

processors:
  trim-prefixes:
    event-strings:
      value-names:
        - ".*"
      transforms:
        - path-base:
            apply-on: "name"
  up-down-map:
    event-strings:
      value-names:
        - oper-state
      transforms:
        - replace:
            apply-on: "value"
            old: "up"
            new: "1"
        - replace:
            apply-on: "value"
            old: "down"
            new: "0"
